name: Renovate
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  RENOVATE_ONBOARDING: false
  RENOVATE_REPOSITORIES: carlobernardini/renovate-test
  LOG_LEVEL: debug

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
